### ISSUE TITLE
Segmentation fault if `y` has shape `(N,)` for some `N`

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#17]
The following code segfaults:

```Python
import numpy as np
import xcsf.xcsf as x


X = np.arange(-1, 1, 0.01)[:,np.newaxis]
y = np.arange(-1, 1, 0.01)


xcs = x.XCS(1, 1, True)

xcs.MAX_TRIALS = 1000
xcs.condition("hyperrectangle", {"min" : -1, "max" : 1, "spread-min": 0.1, "eta": 0})
xcs.prediction("rls-linear", {"x0": 1, "rls-scale-factor":1000, "rls-lambda": 1})
xcs.action("integer")

xcs.fit(X, y, True)

y_pred = xcs.predict(y)
```

However, if I change `y` to
```Python
y = np.arange(-1, 1, 0.01)[:,np.newaxis]
```
or the equivalent
```Python
y = np.arange(-1, 1, 0.01).reshape(-1, 1)
```
it works.

I'm not sure whether fixing this should be high priority (probably not) or whether adding documentation for this behaviour may suffice.

**Comment by rpreen** [comment]
The supervised fit() function needs 2-D numpy arrays as inputs because it expects (x_dim, n_samples) and  (y_dim, n_samples) so the correct way is to reshape it. 

On the [wiki](https://github.com/rpreen/xcsf/wiki/Python-Library-Usage#supervised-fitting) it does document this, but probably the python function should check the input and print a better message to help.

**Comment by rpreen** [comment]
I've updated the wiki a little to add some more information. Feel free to tweak it if you think it needs to be clearer.

**Comment by dpaetzel** [comment]
Ah, I'm sorry, I must have overlooked that on the wiki. It *does* state that very explicitly.

**Comment by dpaetzel** [comment]
Thank you for making the error message more informative! :slightly_smiling_face:
