### ISSUE TITLE
`max_index` leads to unexpected bias in prediction array

### ISSUE THREAD

**Issue by dpaetzel** [rpreen/xcsf#38]
Whenever there are several best actions with the same state-action value estimates in the prediction array, the user might expect that selecting actions greedily corresponds to choosing one of these action at random *uniformly*. In particular, this is the case when nothing's learned yet and the state-action value estimates of all the actions in the prediction array are equal.

However, the use of `max_index` in [`best action`](https://github.com/rpreen/xcsf/blob/3424fc65b6feb92fc0bcf928896a19975194acec/xcsf/pa.c#L120) results in that the first of these best action candidates is always selected.

This bias does not only concern the first encounter of a state: Consider the case where in a—so far unseen—state the first action's state-action value estimate is selected due to this bias and then updated and it turns out to be ever so slightly better than the default state-action value. In an ε-greedy setting (especially if using high initial ε with decay, which is not unusual), the system then would have to get into this state quite a few times until it finally selects other actions (one could do the math how often it would have to encounter the state but I guess the point gets clear without it :wink: ).

I'm afraid I don't have the time right now to write a patch/PR but wanted to let you know anyways :slightly_smiling_face:

**Comment by rpreen** [comment]
Thanks for this, I can definitely see how this might help early learning performance in some problems -- particularly the cartpole example may benefit . The `max_index()` is a simple `argmax()` ([numpy argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) behaves the same, returning the first occurrence in a tie; so that'll mean updating the Python examples that implement the `egreedy()` functions to make the decisions as well as the c function). I'll try to fix this when I can.

**Comment by dpaetzel** [comment]
That was fast! Nice, thank you! :slightly_smiling_face:
